apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqubetest
  labels:
    app: sonarqubetest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqubetest
        tier: frontend
    spec:
      containers:
      - image: registry.au-syd.bluemix.net/liberty_syd/sonarqubetest:2.0
        name: sonarqubetest
        imagePullPolicy: Always
        args:
        - -Dsonar.web.context=/sonar
        ports:
        - containerPort: 9000
